apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: odysseia
deploy:
  kubeContext: k3d-odysseia
  tolerateFailuresUntilDeadline: true

build:
  local:
    push: false

profiles:
  - name: alexandros
    build:
      artifacts:
        - image: ghcr.io/odysseia-greek/alexandros
          context: ./alexandros
          docker:
            target: debug
          sync:
            manual:
              - src: '**/*.go'
                dest: '/app'
    deploy:
      helm:
        releases:
          - name: alexandros
            chartPath: ../../odysseia-greek/mykenai/themistokles/odysseia/charts/alexandros
            valuesFiles:
              - ../../odysseia-greek/mykenai/themistokles/odysseia/values/local.yaml
              - ../../odysseia-greek/mykenai/themistokles/odysseia/values/skaffold-values.yaml
            setValues:
              image.odysseiaapi.repo: alexandros
              image.odysseiaapi.tag: dev
              image.seeder.repo: demokritos
              image.seeder.tag: v0.0.15
  - name: demokritos
    build:
      artifacts:
        - image: ghcr.io/odysseia-greek/demokritos
          context: ./demokritos
          docker:
            target: debug
          sync:
            manual:
              - src: '**/*.go'
                dest: '/app'
    deploy:
      helm:
        releases:
          - name: alexandros
            chartPath: ../../odysseia-greek/mykenai/themistokles/odysseia/charts/alexandros
            valuesFiles:
              - ../../odysseia-greek/mykenai/themistokles/odysseia/values/local.yaml
              - ../../odysseia-greek/mykenai/themistokles/odysseia/values/skaffold-values.yaml
            setValues:
              image.odysseiaapi.repo: alexandros
              image.odysseiaapi.tag: v0.0.14
              image.seeder.repo: demokritos
              image.seeder.tag: dev
  - name: diogenes
    build:
      artifacts:
        - image: ghcr.io/odysseia-greek/diogenes
          context: ./diogenes
          docker:
            target: prod
          sync:
            manual:
              - src: '**/*.go'
                dest: '/app'
    deploy:
      helm:
        releases:
          - name: diogenes
            chartPath: ../../odysseia-greek/mykenai/themistokles/odysseia/charts/diogenes
            valuesFiles:
              - ../../odysseia-greek/mykenai/themistokles/odysseia/values/local.yaml
              - ../../odysseia-greek/mykenai/themistokles/odysseia/values/skaffold-values.yaml
            setValues:
              image.odysseiaapi.repo: diogenes
              image.odysseiaapi.tag: dev

