apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: odysseia
deploy:
  kubeContext: k3d-odysseia
  tolerateFailuresUntilDeadline: true
build:
  local:
    push: false
  artifacts:
    - image: ghcr.io/odysseia-greek/alexandros
      context: alexandros
      docker:
        target: debug
      sync:
        manual:
          - src: '**/*.go'
            dest: '/app'

manifests:
  rawYaml:
    - alexandros/infra/manifest.yaml
profiles:
  - name: dev
