  - name: diogenes
    namespace: odysseia
    chart: ./charts/diogenes
    version: 0.1.1
    missingFileHandler: Error
    labels:
      tier: backend
    needs:
      - odysseia/solon
    values:
      - values/{{ .Environment.Name }}.yaml
      - images:
          odysseiaapi:
            repo: diogenes
            tag: v0.0.14
    set:
      - name: replicas
        value: {{ .Values.diogenes.replicas }}
