profiles:
  - name: diogenes
    build:
      artifacts:
        - image: ghcr.io/odysseia-greek/diogenes
          context: ./diogenes
          docker:
            target: debug
          sync:
            manual:
              - src: '**/*.go'
                dest: '/app'
    deploy:
      helm:
        releases:
          - name: diogenes
            chartPath: ../../odysseia-greek/mykenai/themistokles/odysseia/charts/diogenes
            valuesFiles:
              - ../../odysseia-greek/mykenai/themistokles/odysseia/values/local.yaml
              - ../../odysseia-greek/mykenai/themistokles/odysseia/values/skaffold-values.yaml
            setValues:
              image.odysseiaapi.repo: diogenes
              image.odysseiaapi.tag: dev
