---
# Source: protagoras/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: protagoras
  namespace: odysseia
data:
  ENV: "localdev"
  HERODOTOS_SERVICE: "http://herodotos:5000"
  DIONYSIOS_SERVICE: "http://dionysios:5000"
---
# Source: protagoras/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: protagoras
  namespace: odysseia
  labels:
    heritage: "Helm"
    release: "protagoras"
    chart: "protagoras"
    env: localdev
    variant: k3d
    app: protagoras
spec:
  template:
    metadata:
      labels:
        app: protagoras
        release: protagoras
        version: v0.0.11
    spec:
      containers:
        - name: "protagoras"
          image: ghcr.io/odysseia-greek/protagoras:v0.0.11
          imagePullPolicy: Never
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: protagoras
          ports:
            - containerPort: 2345
              name: delve
      restartPolicy: Never
      volumes:
        - name: vault-server-tls
          secret:
            secretName: vault-server-tls
        - name: solon-certs
          secret:
            secretName: solon-tls-certs
  backoffLimit: 3
---
apiVersion: v1
kind: Service
metadata:
  name: protagoras
spec:
  ports:
    - port: 2345
      name: delve
      targetPort: delve
  selector:
    app: protagoras
