root = "/app"

[build]
cmd = 'go test -gcflags "all=-N -l" github.com/odysseia-greek/olympia/hippokrates .'
bin = "/app/hippokrates"
full_bin = "dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec /app/hippokrates"
watch = ["./..."]
include_ext = ["go", "tpl", "tmpl", "html"]
