---
# Source: hippokrates/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hippokrates
  namespace: odysseia
data:
  ENV: "localdev"
  TLS_ENABLED: "true"
  CERT_ROOT: "/etc/certs"
  ALEXANDROS_SERVICE: "http://alexandros:5000"
  DIONYSIOS_SERVICE: "http://dionysios:5000"
  HERODOTOS_SERVICE: "http://herodotos:5000"
  SOKRATES_SERVICE: "http://sokrates:5000"
  SOLON_SERVICE: "http://solon:5000"
  HOMEROS_SERVICE: "http://homeros:8080"
  ARISTARCHOS_SERVICE: "http://aristarchos:50053"

---
# Source: hippokrates/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hippokrates
  namespace: odysseia
  labels:
    heritage: "Helm"
    release: "hippokrates"
    chart: "hippokrates"
    env: localdev
    variant: k3d
    app: hippokrates
    domain: "backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hippokrates
  template:
    metadata:
      labels:
        app: hippokrates
        release: hippokrates
        version: v0.0.11
    spec:
      containers:
        - name: "hippokrates"
          image: ghcr.io/odysseia-greek/hippokrates:v0.0.11
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: hippokrates
          volumeMounts:
            - name: solon-certs
              mountPath: /etc/certs/solon
              readOnly: true
          ports:
            - containerPort: 2345
              name: delve
---
apiVersion: v1
kind: Service
metadata:
  name: hippokrates
spec:
  ports:
    - port: 2345
      name: delve
      targetPort: delve
  selector:
    app: hippokrates
