package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"encoding/json"

	"github.com/odysseia-greek/olympia/homeros/graph/model"
)

// DictionaryMeta is the resolver for the dictionaryMeta field.
func (r *queryResolver) DictionaryMeta(ctx context.Context) (*model.DictionaryMeta, error) {
	data, err := r.Handler.ForwardToAlexandros(ctx)
	if err != nil {
		return nil, err
	}

	var result struct {
		Data struct {
			DictionaryMeta *model.DictionaryMeta `json:"dictionaryMeta"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	return result.Data.DictionaryMeta, nil
}

// RandomExtendedWords is the resolver for the randomExtendedWords field.
func (r *queryResolver) RandomExtendedWords(ctx context.Context, amount *int32) (*model.RandomExtendedWords, error) {
	data, err := r.Handler.ForwardToAlexandros(ctx)
	if err != nil {
		return nil, err
	}

	var result struct {
		Data struct {
			RandomExtendedWords *model.RandomExtendedWords `json:"randomExtendedWords"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	return result.Data.RandomExtendedWords, nil
}

// CounterTopFive is the resolver for the counterTopFive field.
func (r *queryResolver) CounterTopFive(ctx context.Context) (*model.EukleidesTopFiveResponse, error) {
	data, err := r.Handler.ForwardToAlexandros(ctx)
	if err != nil {
		return nil, err
	}

	var result struct {
		Data struct {
			TopFive *model.EukleidesTopFiveResponse `json:"counterTopFive"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	return result.Data.TopFive, nil
}

// CounterService is the resolver for the counterService field.
func (r *queryResolver) CounterService(ctx context.Context, name string) (*model.EukleidesTopFive, error) {
	data, err := r.Handler.ForwardToAlexandros(ctx)
	if err != nil {
		return nil, err
	}

	var result struct {
		Data struct {
			TopFive *model.EukleidesTopFive `json:"counterService"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	return result.Data.TopFive, nil
}

// CounterSession is the resolver for the counterSession field.
func (r *queryResolver) CounterSession(ctx context.Context, sessionID string) (*model.EukleidesTopFiveResponse, error) {
	data, err := r.Handler.ForwardToAlexandros(ctx)
	if err != nil {
		return nil, err
	}

	var result struct {
		Data struct {
			TopFive *model.EukleidesTopFiveResponse `json:"counterTopFive"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	return result.Data.TopFive, nil
}

// Text is the resolver for the text field.
func (r *queryResolver) Text(ctx context.Context, input model.ExpandableSearchQueryInput) (*model.ExtendedResponse, error) {
	data, err := r.Handler.ForwardToAlexandros(ctx)
	if err != nil {
		return nil, err
	}

	var result struct {
		Data struct {
			Text *model.ExtendedResponse `json:"text"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	return result.Data.Text, nil
}

// Fuzzy is the resolver for the fuzzy field.
func (r *queryResolver) Fuzzy(ctx context.Context, input model.SearchQueryInput) (*model.SearchResponse, error) {
	data, err := r.Handler.ForwardToAlexandros(ctx)
	if err != nil {
		return nil, err
	}

	var result struct {
		Data struct {
			Fuzzy *model.SearchResponse `json:"fuzzy"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	return result.Data.Fuzzy, nil
}

// Exact is the resolver for the exact field.
func (r *queryResolver) Exact(ctx context.Context, input model.ExpandableSearchQueryInput) (*model.ExtendedResponse, error) {
	data, err := r.Handler.ForwardToAlexandros(ctx)
	if err != nil {
		return nil, err
	}

	var result struct {
		Data struct {
			Exact *model.ExtendedResponse `json:"exact"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	return result.Data.Exact, nil
}

// Phrase is the resolver for the phrase field.
func (r *queryResolver) Phrase(ctx context.Context, input model.SearchQueryInput) (*model.SearchResponse, error) {
	data, err := r.Handler.ForwardToAlexandros(ctx)
	if err != nil {
		return nil, err
	}

	var result struct {
		Data struct {
			Phrase *model.SearchResponse `json:"phrase"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	return result.Data.Phrase, nil
}

// Partial is the resolver for the partial field.
func (r *queryResolver) Partial(ctx context.Context, input model.SearchQueryInput) (*model.SearchResponse, error) {
	data, err := r.Handler.ForwardToAlexandros(ctx)
	if err != nil {
		return nil, err
	}

	var result struct {
		Data struct {
			Partial *model.SearchResponse `json:"partial"`
		} `json:"data"`
	}
	if err := json.Unmarshal(data, &result); err != nil {
		return nil, err
	}

	return result.Data.Partial, nil
}
