package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/odysseia-greek/olympia/homeros/graph/model"
)

// HerodotosHealth is the resolver for the herodotosHealth field.
func (r *queryResolver) HerodotosHealth(ctx context.Context) (*model.Health, error) {
	result := &model.Health{}
	err := r.Handler.QueryHerodotos(ctx, `query { health { healthy time version } }`, nil, "health", result)
	return result, err
}

// CorpusHealth is the resolver for the corpusHealth field.
func (r *queryResolver) CorpusHealth(ctx context.Context) (*model.Health, error) {
	result := &model.Health{}
	err := r.Handler.QueryHerodotos(ctx, `query { corpusHealth { healthy time version } }`, nil, "corpusHealth", result)
	return result, err
}

// CorpusOptions is the resolver for the corpusOptions field.
func (r *queryResolver) CorpusOptions(ctx context.Context) (*model.CorpusOptions, error) {
	result := &model.CorpusOptions{}
	err := r.Handler.QueryHerodotos(ctx, `query { corpusOptions { authors { name books { name references { name sections } } } } }`, nil, "corpusOptions", result)
	return result, err
}

// ChapterOptions is the resolver for the chapterOptions field.
func (r *queryResolver) ChapterOptions(ctx context.Context) (*model.ChapterOptions, error) {
	result := &model.ChapterOptions{}
	err := r.Handler.QueryHerodotos(ctx, `query { chapterOptions { chapters { chapter title order level } } }`, nil, "chapterOptions", result)
	return result, err
}

// Chapter is the resolver for the chapter field.
func (r *queryResolver) Chapter(ctx context.Context, chapter string) (*model.Chapter, error) {
	result := &model.Chapter{}
	query := `query Chapter($chapter: String!) { chapter(chapter: $chapter) { chapter title description context order level grammar { grammar title explanation example { greek translation note } } vocabulary { greek translation } texts { text title type source { author work reference dialect } greek readingHints } } }`
	err := r.Handler.QueryHerodotos(ctx, query, map[string]any{"chapter": chapter}, "chapter", result)
	return result, err
}

// CorpusText is the resolver for the corpusText field.
func (r *queryResolver) CorpusText(ctx context.Context, input model.TextInput) (*model.Text, error) {
	result := &model.Text{}
	query := `query CorpusText($input: TextInput!) { text(input: $input) { author book type reference perseusTextLink passages { greek translations section } } }`
	err := r.Handler.QueryHerodotos(ctx, query, map[string]any{"input": input}, "text", result)
	return result, err
}

// CheckChapter is the resolver for the checkChapter field.
func (r *queryResolver) CheckChapter(ctx context.Context, input model.CheckChapterInput) (*model.CheckChapterResult, error) {
	result := &model.CheckChapterResult{}
	query := `query CheckChapter($input: CheckChapterInput!) { checkChapter(input: $input) { chapter texts { text sourceText actualText learnerText } } }`
	err := r.Handler.QueryHerodotos(ctx, query, map[string]any{"input": input}, "checkChapter", result)
	return result, err
}

// CheckText is the resolver for the checkText field.
func (r *queryResolver) CheckText(ctx context.Context, input model.CheckTextInput) (*model.CheckTextResult, error) {
	result := &model.CheckTextResult{}
	query := `query CheckText($input: CheckTextInput!) { checkText(input: $input) { averageLevenshteinPercentage sections { section levenshteinPercentage quizSentence answerSentence } possibleTypos { source provided } } }`
	err := r.Handler.QueryHerodotos(ctx, query, map[string]any{"input": input}, "checkText", result)
	return result, err
}
