package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"

	"github.com/odysseia-greek/agora/plato/config"
	"github.com/odysseia-greek/olympia/homeros/graph/model"
)

// Analyze is the resolver for the analyze field.
func (r *queryResolver) Analyze(ctx context.Context, rootword *string) (*model.AnalyzeTextResponse, error) {
	requestID, _ := ctx.Value(config.HeaderKey).(string)
	return r.Resolver.Handler.Analyze(ctx, *rootword, requestID)
}

// Grammar is the resolver for the grammar field.
func (r *queryResolver) Grammar(ctx context.Context, word *string, includeAudit *bool) (*model.DeclensionTranslationResult, error) {
	requestID, _ := ctx.Value(config.HeaderKey).(string)
	audit := includeAudit != nil && *includeAudit
	return r.Resolver.Handler.Grammar(ctx, *word, requestID, audit)
}

// Sentence is the resolver for the sentence field.
func (r *queryResolver) Sentence(ctx context.Context, text string, includeAudit *bool) (*model.DionysiosSentenceResponse, error) {
	requestID, _ := ctx.Value(config.HeaderKey).(string)
	sessionID, _ := ctx.Value(config.SessionIdKey).(string)
	audit := includeAudit != nil && *includeAudit
	return r.Resolver.Handler.Sentence(ctx, text, sessionID, requestID, audit)
}
