apiVersion: v2
appVersion: 0.8.0
description: A dictionary service within odysseia-greek.
name: alexandros
version: 0.1.1
home: https://www.odysseia-greek.com
sources:
  - https://github.com/odysseia-greek/olympia
  - https://github.com/odysseia-greek/olympia/tree/main/alexandros
dependencies:
  - name: koinos
    version: ">= 0.1.0"
    repository: "file://../koinos"