---
# Source: sokrates/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sokrates
  namespace: odysseia
data:
  ELASTIC_SEARCH_SERVICE: "https://aristoteles-es-http:9200"
  ENV: "localdev"
  TLS_ENABLED: "true"
  CERT_ROOT: "/etc/certs"
  SOLON_SERVICE: "https://solon:5443"
  ALEXANDROS_SERVICE: "http://alexandros:5000"
  HERODOTOS_SERVICE: "http://herodotos:5000"
---
# Source: sokrates/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sokrates
  namespace: odysseia
  labels:
    heritage: "Helm"
    release: "sokrates"
    chart: "sokrates"
    env: localdev
    variant: k3d
    app: sokrates
    domain: "backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sokrates
  template:
    metadata:
      labels:
        app: sokrates
        release: sokrates
        version: v0.0.11
      annotations:
        odysseia-greek/role: hybrid
        odysseia-greek/access: quiz
        perikles/accesses: solon
    spec:
      initContainers:
        - name: "periandros"
          image: ghcr.io/odysseia-greek/periandros:v0.0.11

          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ELASTIC_ROLE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/role']
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: sokrates
          volumeMounts:
            - name: solon-certs
              mountPath: /etc/certs/solon
              readOnly: true
      containers:
        - name: "ptolemaios"
          image: ghcr.io/odysseia-greek/ptolemaios:v0.0.11

          env:
            - name: VAULT_SERVICE
              value: https://vault:8200
            - name: VAULT_TLS
              value:  "true"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: sokrates
          ports:
            - containerPort: 50051
          volumeMounts:
            - name: vault-server-tls
              mountPath: /etc/certs/vault
              readOnly: true
            - name: solon-certs
              mountPath: /etc/certs/solon
              readOnly: true
          imagePullPolicy: Always
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 100m
        - name: "aristophanes"
          image: ghcr.io/odysseia-greek/aristophanes:v0.0.11

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ELASTIC_SEARCH_USER
              valueFrom:
                secretKeyRef:
                  name: agreus-elastic
                  key: user
            - name: ELASTIC_SEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agreus-elastic
                  key: password
          envFrom:
            - configMapRef:
                name: sokrates
          ports:
            - containerPort: 50052
          imagePullPolicy: Always
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 200m
          volumeMounts:
            - name: elastic-internal-tls
              mountPath: /app/config/elastic
              readOnly: true
        - name: "sokrates"
          image: ghcr.io/odysseia-greek/sokrates:v0.0.11

          imagePullPolicy: Never
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: sokrates
          volumeMounts:
            - name: solon-certs
              mountPath: /etc/certs/solon
              readOnly: true
          ports:
            - containerPort: 5000
              name: http
            - containerPort: 2345
              name: delve
      volumes:
        - name: vault-server-tls
          secret:
            secretName: vault-server-tls
        - name: elastic-internal-tls
          secret:
            secretName: aristoteles-es-http-certs-public
        - name: solon-certs
          secret:
            secretName: solon-tls-certs
---
apiVersion: v1
kind: Service
metadata:
  name: sokrates
spec:
  ports:
    - port: 5000
      name: http
      targetPort: http
    - port: 2345
      name: delve
      targetPort: delve
  selector:
    app: sokrates
