// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: hypatia.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hypatia_TrackEvents_FullMethodName        = "/olympia_hypatia.Hypatia/TrackEvents"
	Hypatia_GetEventsBySession_FullMethodName = "/olympia_hypatia.Hypatia/GetEventsBySession"
	Hypatia_GetEventsByPath_FullMethodName    = "/olympia_hypatia.Hypatia/GetEventsByPath"
	Hypatia_GetRecentEvents_FullMethodName    = "/olympia_hypatia.Hypatia/GetRecentEvents"
	Hypatia_Health_FullMethodName             = "/olympia_hypatia.Hypatia/Health"
)

// HypatiaClient is the client API for Hypatia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HypatiaClient interface {
	TrackEvents(ctx context.Context, in *RequestEventBatch, opts ...grpc.CallOption) (*TrackResponse, error)
	GetEventsBySession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*EventsResponse, error)
	GetEventsByPath(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*EventsResponse, error)
	GetRecentEvents(ctx context.Context, in *RecentRequest, opts ...grpc.CallOption) (*EventsResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type hypatiaClient struct {
	cc grpc.ClientConnInterface
}

func NewHypatiaClient(cc grpc.ClientConnInterface) HypatiaClient {
	return &hypatiaClient{cc}
}

func (c *hypatiaClient) TrackEvents(ctx context.Context, in *RequestEventBatch, opts ...grpc.CallOption) (*TrackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TrackResponse)
	err := c.cc.Invoke(ctx, Hypatia_TrackEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypatiaClient) GetEventsBySession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*EventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsResponse)
	err := c.cc.Invoke(ctx, Hypatia_GetEventsBySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypatiaClient) GetEventsByPath(ctx context.Context, in *PathRequest, opts ...grpc.CallOption) (*EventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsResponse)
	err := c.cc.Invoke(ctx, Hypatia_GetEventsByPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypatiaClient) GetRecentEvents(ctx context.Context, in *RecentRequest, opts ...grpc.CallOption) (*EventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventsResponse)
	err := c.cc.Invoke(ctx, Hypatia_GetRecentEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hypatiaClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Hypatia_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HypatiaServer is the server API for Hypatia service.
// All implementations must embed UnimplementedHypatiaServer
// for forward compatibility.
type HypatiaServer interface {
	TrackEvents(context.Context, *RequestEventBatch) (*TrackResponse, error)
	GetEventsBySession(context.Context, *SessionRequest) (*EventsResponse, error)
	GetEventsByPath(context.Context, *PathRequest) (*EventsResponse, error)
	GetRecentEvents(context.Context, *RecentRequest) (*EventsResponse, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedHypatiaServer()
}

// UnimplementedHypatiaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHypatiaServer struct{}

func (UnimplementedHypatiaServer) TrackEvents(context.Context, *RequestEventBatch) (*TrackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackEvents not implemented")
}
func (UnimplementedHypatiaServer) GetEventsBySession(context.Context, *SessionRequest) (*EventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsBySession not implemented")
}
func (UnimplementedHypatiaServer) GetEventsByPath(context.Context, *PathRequest) (*EventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventsByPath not implemented")
}
func (UnimplementedHypatiaServer) GetRecentEvents(context.Context, *RecentRequest) (*EventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecentEvents not implemented")
}
func (UnimplementedHypatiaServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedHypatiaServer) mustEmbedUnimplementedHypatiaServer() {}
func (UnimplementedHypatiaServer) testEmbeddedByValue()                 {}

// UnsafeHypatiaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HypatiaServer will
// result in compilation errors.
type UnsafeHypatiaServer interface {
	mustEmbedUnimplementedHypatiaServer()
}

func RegisterHypatiaServer(s grpc.ServiceRegistrar, srv HypatiaServer) {
	// If the following call panics, it indicates UnimplementedHypatiaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hypatia_ServiceDesc, srv)
}

func _Hypatia_TrackEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEventBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypatiaServer).TrackEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypatia_TrackEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypatiaServer).TrackEvents(ctx, req.(*RequestEventBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypatia_GetEventsBySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypatiaServer).GetEventsBySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypatia_GetEventsBySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypatiaServer).GetEventsBySession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypatia_GetEventsByPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypatiaServer).GetEventsByPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypatia_GetEventsByPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypatiaServer).GetEventsByPath(ctx, req.(*PathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypatia_GetRecentEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypatiaServer).GetRecentEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypatia_GetRecentEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypatiaServer).GetRecentEvents(ctx, req.(*RecentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hypatia_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HypatiaServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hypatia_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HypatiaServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hypatia_ServiceDesc is the grpc.ServiceDesc for Hypatia service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hypatia_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "olympia_hypatia.Hypatia",
	HandlerType: (*HypatiaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TrackEvents",
			Handler:    _Hypatia_TrackEvents_Handler,
		},
		{
			MethodName: "GetEventsBySession",
			Handler:    _Hypatia_GetEventsBySession_Handler,
		},
		{
			MethodName: "GetEventsByPath",
			Handler:    _Hypatia_GetEventsByPath_Handler,
		},
		{
			MethodName: "GetRecentEvents",
			Handler:    _Hypatia_GetRecentEvents_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Hypatia_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hypatia.proto",
}
