// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        (unknown)
// source: hypatia.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Ip            string                 `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	UserAgent     string                 `protobuf:"bytes,6,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Referrer      string                 `protobuf:"bytes,7,opt,name=referrer,proto3" json:"referrer,omitempty"`
	SessionId     string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEvent) Reset() {
	*x = RequestEvent{}
	mi := &file_hypatia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEvent) ProtoMessage() {}

func (x *RequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hypatia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEvent.ProtoReflect.Descriptor instead.
func (*RequestEvent) Descriptor() ([]byte, []int) {
	return file_hypatia_proto_rawDescGZIP(), []int{0}
}

func (x *RequestEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *RequestEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RequestEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestEvent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RequestEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *RequestEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RequestEvent) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *RequestEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RequestEventBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RequestEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestEventBatch) Reset() {
	*x = RequestEventBatch{}
	mi := &file_hypatia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEventBatch) ProtoMessage() {}

func (x *RequestEventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_hypatia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEventBatch.ProtoReflect.Descriptor instead.
func (*RequestEventBatch) Descriptor() ([]byte, []int) {
	return file_hypatia_proto_rawDescGZIP(), []int{1}
}

func (x *RequestEventBatch) GetEvents() []*RequestEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ack           string                 `protobuf:"bytes,1,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackResponse) Reset() {
	*x = TrackResponse{}
	mi := &file_hypatia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackResponse) ProtoMessage() {}

func (x *TrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypatia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackResponse.ProtoReflect.Descriptor instead.
func (*TrackResponse) Descriptor() ([]byte, []int) {
	return file_hypatia_proto_rawDescGZIP(), []int{2}
}

func (x *TrackResponse) GetAck() string {
	if x != nil {
		return x.Ack
	}
	return ""
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_hypatia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypatia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_hypatia_proto_rawDescGZIP(), []int{3}
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathRequest) Reset() {
	*x = PathRequest{}
	mi := &file_hypatia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathRequest) ProtoMessage() {}

func (x *PathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypatia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathRequest.ProtoReflect.Descriptor instead.
func (*PathRequest) Descriptor() ([]byte, []int) {
	return file_hypatia_proto_rawDescGZIP(), []int{4}
}

func (x *PathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RecentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecentRequest) Reset() {
	*x = RecentRequest{}
	mi := &file_hypatia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecentRequest) ProtoMessage() {}

func (x *RecentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypatia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecentRequest.ProtoReflect.Descriptor instead.
func (*RecentRequest) Descriptor() ([]byte, []int) {
	return file_hypatia_proto_rawDescGZIP(), []int{5}
}

func (x *RecentRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type EventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*RequestEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResponse) Reset() {
	*x = EventsResponse{}
	mi := &file_hypatia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResponse) ProtoMessage() {}

func (x *EventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypatia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResponse.ProtoReflect.Descriptor instead.
func (*EventsResponse) Descriptor() ([]byte, []int) {
	return file_hypatia_proto_rawDescGZIP(), []int{6}
}

func (x *EventsResponse) GetEvents() []*RequestEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_hypatia_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypatia_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_hypatia_proto_rawDescGZIP(), []int{7}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_hypatia_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypatia_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_hypatia_proto_rawDescGZIP(), []int{8}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_hypatia_proto protoreflect.FileDescriptor

const file_hypatia_proto_rawDesc = "" +
	"\n" +
	"\rhypatia.proto\x12\x0folympia_hypatia\"\xda\x01\n" +
	"\fRequestEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x0e\n" +
	"\x02ip\x18\x05 \x01(\tR\x02ip\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x06 \x01(\tR\tuserAgent\x12\x1a\n" +
	"\breferrer\x18\a \x01(\tR\breferrer\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\"J\n" +
	"\x11RequestEventBatch\x125\n" +
	"\x06events\x18\x01 \x03(\v2\x1d.olympia_hypatia.RequestEventR\x06events\"!\n" +
	"\rTrackResponse\x12\x10\n" +
	"\x03ack\x18\x01 \x01(\tR\x03ack\"/\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"!\n" +
	"\vPathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"%\n" +
	"\rRecentRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"G\n" +
	"\x0eEventsResponse\x125\n" +
	"\x06events\x18\x01 \x03(\v2\x1d.olympia_hypatia.RequestEventR\x06events\"\x0f\n" +
	"\rHealthRequest\"X\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion2\xaf\x03\n" +
	"\aHypatia\x12S\n" +
	"\vTrackEvents\x12\".olympia_hypatia.RequestEventBatch\x1a\x1e.olympia_hypatia.TrackResponse\"\x00\x12X\n" +
	"\x12GetEventsBySession\x12\x1f.olympia_hypatia.SessionRequest\x1a\x1f.olympia_hypatia.EventsResponse\"\x00\x12R\n" +
	"\x0fGetEventsByPath\x12\x1c.olympia_hypatia.PathRequest\x1a\x1f.olympia_hypatia.EventsResponse\"\x00\x12T\n" +
	"\x0fGetRecentEvents\x12\x1e.olympia_hypatia.RecentRequest\x1a\x1f.olympia_hypatia.EventsResponse\"\x00\x12K\n" +
	"\x06Health\x12\x1e.olympia_hypatia.HealthRequest\x1a\x1f.olympia_hypatia.HealthResponse\"\x00B\xaf\x01\n" +
	"\x13com.olympia_hypatiaB\fHypatiaProtoP\x01Z2github.com/odysseia-greek/olympia/hypatia/proto/v1\xa2\x02\x03OXX\xaa\x02\x0eOlympiaHypatia\xca\x02\x0eOlympiaHypatia\xe2\x02\x1aOlympiaHypatia\\GPBMetadata\xea\x02\x0eOlympiaHypatiab\x06proto3"

var (
	file_hypatia_proto_rawDescOnce sync.Once
	file_hypatia_proto_rawDescData []byte
)

func file_hypatia_proto_rawDescGZIP() []byte {
	file_hypatia_proto_rawDescOnce.Do(func() {
		file_hypatia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hypatia_proto_rawDesc), len(file_hypatia_proto_rawDesc)))
	})
	return file_hypatia_proto_rawDescData
}

var file_hypatia_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_hypatia_proto_goTypes = []any{
	(*RequestEvent)(nil),      // 0: olympia_hypatia.RequestEvent
	(*RequestEventBatch)(nil), // 1: olympia_hypatia.RequestEventBatch
	(*TrackResponse)(nil),     // 2: olympia_hypatia.TrackResponse
	(*SessionRequest)(nil),    // 3: olympia_hypatia.SessionRequest
	(*PathRequest)(nil),       // 4: olympia_hypatia.PathRequest
	(*RecentRequest)(nil),     // 5: olympia_hypatia.RecentRequest
	(*EventsResponse)(nil),    // 6: olympia_hypatia.EventsResponse
	(*HealthRequest)(nil),     // 7: olympia_hypatia.HealthRequest
	(*HealthResponse)(nil),    // 8: olympia_hypatia.HealthResponse
}
var file_hypatia_proto_depIdxs = []int32{
	0, // 0: olympia_hypatia.RequestEventBatch.events:type_name -> olympia_hypatia.RequestEvent
	0, // 1: olympia_hypatia.EventsResponse.events:type_name -> olympia_hypatia.RequestEvent
	1, // 2: olympia_hypatia.Hypatia.TrackEvents:input_type -> olympia_hypatia.RequestEventBatch
	3, // 3: olympia_hypatia.Hypatia.GetEventsBySession:input_type -> olympia_hypatia.SessionRequest
	4, // 4: olympia_hypatia.Hypatia.GetEventsByPath:input_type -> olympia_hypatia.PathRequest
	5, // 5: olympia_hypatia.Hypatia.GetRecentEvents:input_type -> olympia_hypatia.RecentRequest
	7, // 6: olympia_hypatia.Hypatia.Health:input_type -> olympia_hypatia.HealthRequest
	2, // 7: olympia_hypatia.Hypatia.TrackEvents:output_type -> olympia_hypatia.TrackResponse
	6, // 8: olympia_hypatia.Hypatia.GetEventsBySession:output_type -> olympia_hypatia.EventsResponse
	6, // 9: olympia_hypatia.Hypatia.GetEventsByPath:output_type -> olympia_hypatia.EventsResponse
	6, // 10: olympia_hypatia.Hypatia.GetRecentEvents:output_type -> olympia_hypatia.EventsResponse
	8, // 11: olympia_hypatia.Hypatia.Health:output_type -> olympia_hypatia.HealthResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hypatia_proto_init() }
func file_hypatia_proto_init() {
	if File_hypatia_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hypatia_proto_rawDesc), len(file_hypatia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hypatia_proto_goTypes,
		DependencyIndexes: file_hypatia_proto_depIdxs,
		MessageInfos:      file_hypatia_proto_msgTypes,
	}.Build()
	File_hypatia_proto = out.File
	file_hypatia_proto_goTypes = nil
	file_hypatia_proto_depIdxs = nil
}
