---
# Source: sokrates/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sokrates-dev
  namespace: odysseia
data:
  ELASTIC_SEARCH_SERVICE: "https://aristoteles-es-http:9200"
  ENV: "localdev"
  TLS_ENABLED: "true"
  CERT_ROOT: "/etc/certs"
  SOLON_SERVICE: "https://solon:5443"
  ALEXANDROS_SERVICE: "http://alexandros:5000"
  HERODOTOS_SERVICE: "http://herodotos:5000"
---
# Source: sokrates/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: parmenides
  namespace: odysseia
  labels:
    heritage: "Helm"
    release: "sokrates"
    chart: "sokrates"
    env: localdev
    variant: k3d
    app: parmenides
spec:
  template:
    metadata:
      labels:
        app: parmenides
        release: sokrates
        version: v0.0.11
      annotations:
        odysseia-greek/role: seeder
        odysseia-greek/access: quiz
        perikles/accesses: solon
    spec:
      initContainers:
        - name: "periandros"
          image: ghcr.io/odysseia-greek/periandros:v0.0.11

          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ELASTIC_ROLE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/role']
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: sokrates-dev
          volumeMounts:
            - name: solon-certs
              mountPath: /etc/certs/solon
              readOnly: true
      containers:
        - name: "ptolemaios"
          image: ghcr.io/odysseia-greek/ptolemaios:v0.0.11

          env:
            - name: VAULT_SERVICE
              value: https://vault:8200
            - name: VAULT_TLS
              value:  "true"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: sokrates-dev
          ports:
            - containerPort: 50051
          volumeMounts:
            - name: vault-server-tls
              mountPath: /etc/certs/vault
              readOnly: true
            - name: solon-certs
              mountPath: /etc/certs/solon
              readOnly: true
          imagePullPolicy: Always
          resources:
            requests:
              memory: 32Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 100m
        - name: "parmenides"
          image: ghcr.io/odysseia-greek/parmenides:v0.0.11
          imagePullPolicy: Never

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ELASTIC_ACCESS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['odysseia-greek/access']
          envFrom:
            - configMapRef:
                name: sokrates-dev
          ports:
            - containerPort: 2345
              name: delve
      restartPolicy: Never
      volumes:
        - name: vault-server-tls
          secret:
            secretName: vault-server-tls
        - name: solon-certs
          secret:
            secretName: solon-tls-certs
  backoffLimit: 3
---
apiVersion: v1
kind: Service
metadata:
  name: parmenides
spec:
  ports:
    - port: 2345
      name: delve
      targetPort: delve
  selector:
    app: parmenides
